variables:
  - group: ContainerRegistryVariables #this group must contain 2 variables - ContainerRegistryAdminUser & ContainerRegistryPassword
  - name: AppImageName
    value: vststools-build-agent

resources:
  repositories:
  - repository: self

trigger:
  paths:
    include: 
    - Resources/Dockerfiles/BuildAgent/buildagent.Dockerfile
    - Resources/AzureDevOps/buildagent-pipeline.yml

jobs:
- job: BuildAgentImage
  displayName: 'Build Agent Image'
  pool: 'Hosted Ubuntu 1604'

  steps:
  - script: |
      cd ./Resources/Dockerfiles/BuildAgent
      docker build -t $(ContainerRegistryAdminUser).azurecr.io/$(AppImageName) --file buildagent.Dockerfile .
    displayName: 'Build app container'
  - script: |
      docker login -u $(ContainerRegistryAdminUser) -p $(ContainerRegistryPassword) $(ContainerRegistryAdminUser).azurecr.io
      docker push $(ContainerRegistryAdminUser).azurecr.io/$(AppImageName)
    displayName: 'Publish app container'